name: 20 SCA

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: SCA JavaScript project
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
        with: 
         ref: ${{ github.event.pull_request.head.sha }} 
    
      - name: Setup Node.js 
        uses: actions/setup-node@v4 
        with: 
          node-version: 20 
      
      - name: Restore cached dependencies 
        id: cache-restore 
        uses: actions/cache@v4
        with: 
          path: ./src/node_modules 
          key: npm-${{ hashFiles('./src/package-lock.json') }} 
      
      - name: Install dependencies 
        if: steps.cache-restore.outputs.cache-hit != 'true' 
        run: | 
          cd src 
          npm ci - ignore-scripts 
        
      - name: Lint 
        run: | 
          cd src 
          npm run lint
          
      #install SCA tool (SonarQube)
      #- name: SonarQube Scan
      #  uses: sonarsource/sonarqube-scan-action@master
      #  with:
      #    projectBaseDir: .
      #    args: >
      #      -Dsonar.organization=my-org
      #      -Dsonar.projectKey=my-Java-web-app
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}    
      #install SCA tool (Checkmarx)  
      #- name: Install SCA tool (Checkmarx AST CLI Action)
      #  uses: checkmarx/ast-github-action@main #Github Action version
      #  with:
      #    base_uri: https://ast.checkmarx.net/
      #    cx_tenant: your_tenant
      #    cx_client_id: ${{ secrets.CX_CLIENT_ID }}
      #    cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}

         